[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.padding]
x = 8
y = 10
