[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 300
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[window]
decorations = 'Buttonless'
dynamic_padding = false
opacity = 0.65
blur = true
dynamic_title = true

[window.padding]
x = 4
y = 4

[font]
size = 14
normal = {family="JetBrains Mono", style="Regular"}

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[general]
import = [
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]
