import = [
    "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 300
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 8
y = 8

[font]
size = 13
normal = {family="JetBrains Mono", style="Regular"}

